import Head from "next/head";

const about = () => {
  return (
    <>
      <Head>
        <title>WebDev News | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="web, development, crash course, news" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>About</h1>
      </main>
    </>
  );
};

export default about;
